@startuml

hide empty description

state NoRalentizado
state Ralentizado

NoRalentizado -> Ralentizado: ralentizado()
Ralentizado -> NoRalentizado: mover()

note on link
Los enemigos se ralentizan cuando pisan
una Trampa Arenosa y vuelven a moverse
con normalidad luego de un turno
end note


footer Enemigo pasa a estar ralentizado

@enduml